
obs_topics:
  # /franka_gripper/joint_states: joint_states 
  /franka_state_controller/joint_states_desired: joint_states_desired
  /franka_state_controller/O_T_EE: O_T_EE
  /franka_state_controller/ee_pose: ee_pose
  /franka_state_controller/joint_states: joint_states

action_topics:
  /cartesian_impedance_controller/desired_pose
  # Will add gripper later

mask: true