
obs_topics:
  /franka_state_controller/ee_pose: ee_pose
  /franka_gripper/joint_states: gripper_joint_states 
  /franka_state_controller/joint_states_desired: joint_states_desired
  /franka_state_controller/O_T_EE: O_T_EE
  /franka_state_controller/joint_states: joint_states
  /zedA/zed_node_A/left/image_rect_color: front_camera
  /zedB/zed_node_B/left/image_rect_color: back_camera

action_topics:
  /cartesian_impedance_controller/desired_pose
  # Will infer gripper action from gripper joint states observations

mask: true